section for project in tito.props is not mandatory for CoprReleaser
so if it does not exist, create it. This is in-memory operation
and does not affect real file.
Also make disttag optional. If not defined use empty string.

addressing:
Building release in Copr...
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 94, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 639, in main
    scratch=self.options.scratch)
  File "/usr/lib/python2.7/site-packages/tito/release.py", line 998, in release
    self._koji_release()
  File "/usr/lib/python2.7/site-packages/tito/copr.py", line 45, in _koji_release
    KojiReleaser._koji_release(self)
  File "/usr/lib/python2.7/site-packages/tito/release.py", line 1029, in _koji_release
    disttag = self.builder.config.get(koji_tag, "disttag")
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'copr'